version: '3.7'

services:
  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    env_file:
      - server.env
    volumes:
      - ./server:/app
    ports:
      - '5000:5000'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./client:/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - '3000:3000'
