version: '3.7'

services:
  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
